name: GitHub Actions Deploy 
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn workspace @berry/shared build
      - run: node ./node_modules/serverless/bin/serverless.js config credentials --provider aws --key AKIAS3LL6I6S35FZCDIR --secret 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 --profile papaya --overwrite
      - run: node ../../node_modules/serverless/bin/serverless.js deploy --aws-s3-accelerate --stage dev --verbose
        working-directory: ./services/id
        env:
          AWS_ACCESS_KEY_ID: AKIAS3LL6I6S35FZCDIR
          AWS_SECRET_ACCESS_KEY: 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
          SLS_DEBUG: 1